# Stack's standard Travis config, taken from
# http://docs.haskellstack.org/en/stable/GUIDE.html#travis-with-caching



# Use new container infrastructure to enable caching
sudo: false



# Choose a lightweight base image; we provide our own build tools.
language: c



# GHC depends on GMP. You can add other dependencies here as well.
addons:
    apt:
        packages:
            - libgmp-dev



# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
    # LTS 1 and 2 use uses GHC 7.8.4
    - >
      STACK_ARGS="--resolver lts-2 --stack-yaml stack-older-snapshots.yaml"
      STACK_BUILD_ARGS=""
      SKIP_RELEASE_CHECKS=1
    # LTS 3 to 6 all use GHC 7.10.{2,3}
    - >
      STACK_ARGS="--resolver lts-6"
      STACK_BUILD_ARGS=""
      SKIP_RELEASE_CHECKS=1
    # LTS 7, 8 and 9 use GHC 8.0.{1,2}
    - >
      STACK_ARGS="--resolver lts-9"
      STACK_BUILD_ARGS="--ghc-options -Werror"

    - >
      STACK_ARGS="--resolver lts"
      STACK_BUILD_ARGS=""
    - >
      STACK_ARGS="--resolver nightly"
      STACK_BUILD_ARGS="--ghc-options \"-Wcompat -Werror\""



matrix:
    fast_finish: true
    allow_failures:
        - env:
            - >
              STACK_ARGS="--resolver nightly"
              STACK_BUILD_ARGS="--ghc-options \"-Wcompat -Werror\""



before_install:
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - >
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

    - stack $STACK_ARGS --no-terminal setup
    - |
      if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then
          stack $STACK_ARGS --no-terminal install hlint-2.0.9 stylish-haskell-0.8.0.0
      fi



script:
    - >
      travis_wait stack $STACK_ARGS --no-terminal test
      $STACK_BUILD_ARGS
    - >
      travis_wait stack $STACK_ARGS --no-terminal haddock --no-haddock-deps
      $STACK_BUILD_ARGS
    - |
      if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then
          travis_wait stack $STACK_ARGS --no-terminal bench --no-run-benchmarks $STACK_BUILD_ARGS
      fi
    - stack $STACK_ARGS --no-terminal sdist

    - if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then ./scripts/checks/hlint;                    fi
    - if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then ./scripts/checks/readme-was-generated;     fi
    - if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then ./scripts/checks/negated-cpp-macro-syntax; fi
    - if [[ -z "$SKIP_RELEASE_CHECKS" ]]; then ./scripts/checks/stylish-haskell;          fi



# Caching so the next build will be fast too.
cache:
    directories:
        - $HOME/.stack
